#ifndef AEGIS_ERROR_HPP
#define AEGIS_ERROR_HPP

#include <system_error>

namespace aegis::category {

::std::error_category const& async () noexcept;
::std::error_category const& asn1 () noexcept;

::std::error_category const& bignum () noexcept;

::std::error_category const& certificate_management_protocol () noexcept; // CMP_*
::std::error_category const& cryptographic_message_syntax () noexcept; // CMS_*
::std::error_category const& certificate_transparency () noexcept; // CT_*
::std::error_category const& configuration () noexcept;
::std::error_category const& compression () noexcept;
::std::error_category const& crypto () noexcept;

::std::error_category const& diffie_hellman () noexcept;
::std::error_category const& dsa () noexcept;

::std::error_category const& enhanced_security_service () noexcept; // ess
::std::error_category const& elliptic_curve () noexcept;
::std::error_category const& envelope () noexcept; // evp
::std::error_category const& engine () noexcept;

::std::error_category const& generic () noexcept;

::std::error_category const& http () noexcept;

::std::error_category const& io () noexcept;

::std::error_category const& object () noexcept; // asn1 objects
::std::error_category const& ocsp () noexcept;

::std::error_category const& pkcs12 () noexcept;
::std::error_category const& pkcs7 () noexcept;
::std::error_category const& pem () noexcept;

::std::error_category const& random () noexcept;
::std::error_category const& rsa () noexcept;

::std::error_category const& store () noexcept;
::std::error_category const& ssl () noexcept;

::std::error_category const& ts () noexcept; // asn1 ts

::std::error_category const& ui () noexcept;

::std::error_category const& x509v3 () noexcept;
::std::error_category const& x509 () noexcept;

} /* namespace aegis */

namespace aegis::error {

enum class async {
  failed_to_set_pool = 101,
  failed_to_swap_context = 102,
  init_failed = 105,
  invalid_pool_size = 103,
};

enum class asn1 {
  adding_object = 171,
  asn1_parse_error = 203,
  asn1_sig_parse_error = 204,
  aux_error = 100,
  bad_object_header = 102,
  bmpstring_is_wrong_length = 214,
  bn_lib = 105,
  boolean_is_wrong_length = 106,
  buffer_too_small = 107,
  cipher_has_no_object_identifier = 108,
  context_not_initialised = 217,
  data_is_wrong = 109,
  decode_error = 110,
  depth_exceeded = 174,
  digest_and_key_type_not_supported = 198,
  encode_error = 112,
  error_getting_time = 173,
  error_loading_section = 172,
  error_setting_cipher_params = 114,
  expecting_an_integer = 115,
  expecting_an_object = 116,
  explicit_length_mismatch = 119,
  explicit_tag_not_constructed = 120,
  field_missing = 121,
  first_num_too_large = 122,
  header_too_long = 123,
  illegal_bitstring_format = 175,
  illegal_boolean = 176,
  illegal_characters = 124,
  illegal_format = 177,
  illegal_hex = 178,
  illegal_implicit_tag = 179,
  illegal_integer = 180,
  illegal_negative_value = 226,
  illegal_nested_tagging = 181,
  illegal_null = 125,
  illegal_null_value = 182,
  illegal_object = 183,
  illegal_optional_any = 126,
  illegal_options_on_item_template = 170,
  illegal_padding = 221,
  illegal_tagged_any = 127,
  illegal_time_value = 184,
  illegal_zero_content = 222,
  integer_not_ascii_format = 185,
  integer_too_large_for_long = 128,
  invalid_bit_string_bits_left = 220,
  invalid_bmpstring_length = 129,
  invalid_digit = 130,
  invalid_mime_type = 205,
  invalid_modifier = 186,
  invalid_number = 187,
  invalid_object_encoding = 216,
  invalid_scrypt_parameters = 227,
  invalid_separator = 131,
  invalid_string_table_value = 218,
  invalid_universalstring_length = 133,
  invalid_utf8string = 134,
  invalid_value = 219,
  list_error = 188,
  mime_no_content_type = 206,
  mime_parse_error = 207,
  mime_sig_parse_error = 208,
  missing_eoc = 137,
  missing_second_number = 138,
  missing_value = 189,
  mstring_not_universal = 139,
  mstring_wrong_tag = 140,
  nested_asn1_string = 197,
  nested_too_deep = 201,
  non_hex_characters = 141,
  not_ascii_format = 190,
  not_enough_data = 142,
  no_content_type = 209,
  no_matching_choice_type = 143,
  no_multipart_body_failure = 210,
  no_multipart_boundary = 211,
  no_sig_content_type = 212,
  null_is_wrong_length = 144,
  object_not_ascii_format = 191,
  odd_number_of_chars = 145,
  second_number_too_large = 147,
  sequence_length_mismatch = 148,
  sequence_not_constructed = 149,
  sequence_or_set_needs_config = 192,
  short_line = 150,
  sig_invalid_mime_type = 213,
  streaming_not_supported = 202,
  string_too_long = 151,
  string_too_short = 152,
  the_asn1_object_identifier_is_not_known_for_this_md = 154,
  time_not_ascii_format = 193,
  too_large = 223,
  too_long = 155,
  too_small = 224,
  type_not_constructed = 156,
  type_not_primitive = 195,
  unexpected_eoc = 159,
  universalstring_is_wrong_length = 215,
  unknown_format = 160,
  unknown_message_digest_algorithm = 161,
  unknown_object_type = 162,
  unknown_public_key_type = 163,
  unknown_signature_algorithm = 199,
  unknown_tag = 194,
  unsupported_any_defined_by_type = 164,
  unsupported_cipher = 228,
  unsupported_public_key_type = 167,
  unsupported_type = 196,
  wrong_integer_type = 225,
  wrong_public_key_type = 200,
  wrong_tag = 168,
};

enum class bignum {
  arg2_lt_arg3 = 100,
  bad_reciprocal = 101,
  bignum_too_long = 114,
  bits_too_small = 118,
  called_with_even_modulus = 102,
  divide_by_zero = 103,
  encoding_error = 104,
  expand_on_static_bignum_data = 105,
  input_not_reduced = 110,
  invalid_length = 106,
  invalid_range = 115,
  invalid_shift = 119,
  not_a_square = 111,
  not_initialized = 107,
  no_inverse = 108,
  no_solution = 116,
  no_suitable_digest = 120,
  private_key_too_large = 117,
  p_is_not_prime = 112,
  too_many_iterations = 113,
  too_many_temporary_variables = 109,
};

enum class certificate_management_protocol {
  algorithm_not_supported = 139,
  bad_checkafter_in_pollrep = 167,
  bad_request_id = 108,
  certhash_unmatched = 156,
  certid_not_found = 109,
  certificate_not_accepted = 169,
  certificate_not_found = 112,
  certreqmsg_not_found = 157,
  certresponse_not_found = 113,
  cert_and_key_do_not_match = 114,
  checkafter_out_of_range = 181,
  checking_pbm_no_secret_available = 166,
  encountered_keyupdatewarning = 176,
  encountered_waiting = 162,
  error_calculating_protection = 115,
  error_creating_certconf = 116,
  error_creating_certrep = 117,
  error_creating_cr = 163,
  error_creating_error = 118,
  error_creating_genm = 119,
  error_creating_genp = 120,
  error_creating_ir = 164,
  error_creating_kur = 165,
  error_creating_p10cr = 121,
  error_creating_pkiconf = 122,
  error_creating_pollrep = 123,
  error_creating_pollreq = 124,
  error_creating_rp = 125,
  error_creating_rr = 126,
  error_parsing_pkistatus = 107,
  error_processing_message = 158,
  error_protecting_message = 127,
  error_setting_certhash = 128,
  error_unexpected_certconf = 160,
  error_validating_protection = 140,
  failed_extracting_pubkey = 141,
  failure_obtaining_random = 110,
  fail_info_out_of_range = 129,
  invalid_args = 100,
  missing_key_input_for_creating_protection = 130,
  missing_key_usage_digitalsignature = 142,
  missing_private_key = 131,
  missing_protection = 143,
  missing_reference_cert = 168,
  missing_sender_identification = 111,
  missing_trust_store = 144,
  multiple_requests_not_supported = 161,
  multiple_responses_not_supported = 170,
  multiple_san_sources = 102,
  no_stdio = 194,
  no_suitable_sender_cert = 145,
  null_argument = 103,
  pkibody_error = 146,
  pkistatusinfo_not_found = 132,
  polling_failed = 172,
  potentially_invalid_certificate = 147,
  received_error = 180,
  recipnonce_unmatched = 148,
  request_not_accepted = 149,
  request_rejected_by_server = 182,
  sender_generalname_type_not_supported = 150,
  srvcert_does_not_validate_msg = 151,
  total_timeout = 184,
  transactionid_unmatched = 152,
  transfer_error = 159,
  unexpected_pkibody = 133,
  unexpected_pkistatus = 185,
  unexpected_pvno = 153,
  unknown_algorithm_id = 134,
  unknown_cert_type = 135,
  unknown_pkistatus = 186,
  unsupported_algorithm = 136,
  unsupported_key_type = 137,
  unsupported_protection_alg_dhbasedmac = 154,
  wrong_algorithm_oid = 138,
  wrong_certid_in_rp = 187,
  wrong_pbm_value = 155,
  wrong_rp_component_count = 188,
  wrong_serial_in_rp = 173,
};

enum class cryptographic_message_syntax {
  add_signer_error = 99,
  attribute_error = 161,
  certificate_already_present = 175,
  certificate_has_no_keyid = 160,
  certificate_verify_error = 100,
  cipher_initialisation_error = 101,
  cipher_parameter_initialisation_error = 102,
  cms_datafinal_error = 103,
  cms_lib = 104,
  contentidentifier_mismatch = 170,
  content_not_found = 105,
  content_type_mismatch = 171,
  content_type_not_compressed_data = 106,
  content_type_not_enveloped_data = 107,
  content_type_not_signed_data = 108,
  content_verify_error = 109,
  ctrl_error = 110,
  ctrl_failure = 111,
  decrypt_error = 112,
  error_getting_public_key = 113,
  error_reading_messagedigest_attribute = 114,
  error_setting_key = 115,
  error_setting_recipientinfo = 116,
  invalid_encrypted_key_length = 117,
  invalid_key_encryption_parameter = 176,
  invalid_key_length = 118,
  md_bio_init_error = 119,
  messagedigest_attribute_wrong_length = 120,
  messagedigest_wrong_length = 121,
  msgsigdigest_error = 172,
  msgsigdigest_verification_failure = 162,
  msgsigdigest_wrong_length = 163,
  need_one_signer = 164,
  not_a_signed_receipt = 165,
  not_encrypted_data = 122,
  not_kek = 123,
  not_key_agreement = 181,
  not_key_transport = 124,
  not_pwri = 177,
  not_supported_for_this_key_type = 125,
  no_cipher = 126,
  no_content = 127,
  no_content_type = 173,
  no_default_digest = 128,
  no_digest_set = 129,
  no_key = 130,
  no_key_or_cert = 174,
  no_matching_digest = 131,
  no_matching_recipient = 132,
  no_matching_signature = 166,
  no_msgsigdigest = 167,
  no_password = 178,
  no_private_key = 133,
  no_public_key = 134,
  no_receipt_request = 168,
  no_signers = 135,
  private_key_does_not_match_certificate = 136,
  receipt_decode_error = 169,
  recipient_error = 137,
  signer_certificate_not_found = 138,
  signfinal_error = 139,
  smime_text_error = 140,
  store_init_error = 141,
  type_not_compressed_data = 142,
  type_not_data = 143,
  type_not_digested_data = 144,
  type_not_encrypted_data = 145,
  type_not_enveloped_data = 146,
  unable_to_finalize_context = 147,
  unknown_cipher = 148,
  unknown_digest_algorithm = 149,
  unknown_id = 150,
  unsupported_compression_algorithm = 151,
  unsupported_content_type = 152,
  unsupported_kek_algorithm = 153,
  unsupported_key_encryption_algorithm = 179,
  unsupported_recipientinfo_type = 155,
  unsupported_recipient_type = 154,
  unsupported_type = 156,
  unwrap_error = 157,
  unwrap_failure = 180,
  verification_failure = 158,
  wrap_error = 159,
};

enum class certificate_transparency {
  base64_decode_error = 108,
  invalid_log_id_length = 100,
  log_conf_invalid = 109,
  log_conf_invalid_key = 110,
  log_conf_missing_description = 111,
  log_conf_missing_key = 112,
  log_key_invalid = 113,
  sct_future_timestamp = 116,
  sct_invalid = 104,
  sct_invalid_signature = 107,
  sct_list_invalid = 105,
  sct_log_id_mismatch = 114,
  sct_not_set = 106,
  sct_unsupported_version = 115,
  unrecognized_signature_nid = 101,
  unsupported_entry_type = 102,
  unsupported_version = 103,
};

enum class configuration {
  error_loading_dso = 110,
  invalid_pragma = 122,
  list_cannot_be_null = 115,
  mandatory_braces_in_variable_expansion = 123,
  missing_close_square_bracket = 100,
  missing_equal_sign = 101,
  missing_init_function = 112,
  module_initialization_error = 109,
  no_close_brace = 102,
  no_conf = 105,
  no_conf_or_environment_variable = 106,
  no_section = 107,
  no_such_file = 114,
  no_value = 108,
  number_too_large = 121,
  recursive_directory_include = 111,
  ssl_command_section_empty = 117,
  ssl_command_section_not_found = 118,
  ssl_section_empty = 119,
  ssl_section_not_found = 120,
  unable_to_create_new_section = 103,
  unknown_module_name = 113,
  variable_expansion_too_long = 116,
  variable_has_no_value = 104,
};

enum class compression {
  zlib_deflate_error = 99,
  zlib_inflate_error = 100,
  zlib_not_supported = 101,
};

enum class crypto {
  bad_algorithm_name = 117,
  conflicting_names = 118,
  fips_mode_not_supported = 101,
  illegal_hex_digit = 102,
  insufficient_data_space = 106,
  insufficient_param_size = 107,
  insufficient_secure_data_space = 108,
  invalid_null_argument = 109,
  invalid_ossl_param_type = 110,
  odd_number_of_digits = 103,
  provider_already_exists = 104,
  provider_section_error = 105,
  secure_malloc_failure = 111,
  string_too_long = 112,
  too_many_bytes = 113,
  too_many_records = 114,
  too_small_buffer = 116,
  zero_length_number = 115,
};

enum class diffie_hellman {
  bad_generator = 101,
  bn_decode_error = 109,
  bn_error = 106,
  check_invalid_j_value = 115,
  check_invalid_q_value = 116,
  check_pubkey_invalid = 122,
  check_pubkey_too_large = 123,
  check_pubkey_too_small = 124,
  check_p_not_prime = 117,
  check_p_not_safe_prime = 118,
  check_q_not_prime = 119,
  decode_error = 104,
  invalid_parameter_name = 110,
  invalid_parameter_nid = 114,
  invalid_pubkey = 102,
  kdf_parameter_error = 112,
  keys_not_set = 108,
  missing_pubkey = 125,
  modulus_too_large = 103,
  modulus_too_small = 126,
  not_suitable_generator = 120,
  no_parameters_set = 107,
  no_private_value = 100,
  parameter_encoding_error = 105,
  peer_key_error = 111,
  shared_info_error = 113,
  unable_to_check_generator = 121,
};

enum class dsa {
  bad_q_value = 102,
  bn_decode_error = 108,
  bn_error = 109,
  decode_error = 104,
  invalid_digest_type = 106,
  invalid_parameters = 112,
  missing_parameters = 101,
  missing_private_key = 111,
  modulus_too_large = 103,
  no_parameters_set = 107,
  parameter_encoding_error = 105,
  q_not_prime = 113,
  seed_len_small = 110,
};

enum class enhanced_security_service {
  signing_certificate_error = 102,
  signing_cert_add_error = 100,
  signing_cert_v2_add_error = 101,
};

enum class elliptic_curve {
  asn1_error = 115,
  bad_signature = 156,
  bignum_out_of_range = 144,
  buffer_too_small = 100,
  cannot_invert = 165,
  coordinates_out_of_range = 146,
  curve_does_not_support_ecdh = 160,
  curve_does_not_support_ecdsa = 170,
  curve_does_not_support_signing = 159,
  d2i_ecpkparameters_failure = 117,
  decode_error = 142,
  discriminant_is_zero = 118,
  ec_group_new_by_name_failure = 119,
  failed_making_public_key = 166,
  field_too_large = 143,
  gf2m_not_supported = 147,
  group2pkparameters_failure = 120,
  i2d_ecpkparameters_failure = 121,
  incompatible_objects = 101,
  invalid_argument = 112,
  invalid_compressed_point = 110,
  invalid_compression_bit = 109,
  invalid_curve = 141,
  invalid_digest = 151,
  invalid_digest_type = 138,
  invalid_encoding = 102,
  invalid_field = 103,
  invalid_form = 104,
  invalid_group_order = 122,
  invalid_key = 116,
  invalid_output_length = 161,
  invalid_peer_key = 133,
  invalid_pentanomial_basis = 132,
  invalid_private_key = 123,
  invalid_trinomial_basis = 137,
  kdf_parameter_error = 148,
  keys_not_set = 140,
  ladder_post_failure = 136,
  ladder_pre_failure = 153,
  ladder_step_failure = 162,
  missing_parameters = 124,
  missing_private_key = 125,
  need_new_setup_values = 157,
  not_a_nist_prime = 135,
  not_implemented = 126,
  not_initialized = 111,
  no_parameters_set = 139,
  no_private_value = 154,
  operation_not_supported = 152,
  passed_null_parameter = 134,
  peer_key_error = 149,
  pkparameters2group_failure = 127,
  point_arithmetic_failure = 155,
  point_at_infinity = 106,
  point_coordinates_blind_failure = 163,
  point_is_not_on_curve = 107,
  random_number_generation_failed = 158,
  shared_info_error = 150,
  slot_full = 108,
  undefined_generator = 113,
  undefined_order = 128,
  unknown_cofactor = 164,
  unknown_group = 129,
  unknown_order = 114,
  unsupported_field = 131,
  wrong_curve_parameters = 145,
  wrong_order = 130,
};

enum class envelope {
  aes_key_setup_failed = 143,
  aria_key_setup_failed = 176,
  bad_algorithm_name = 200,
  bad_decrypt = 100,
  bad_key_length = 195,
  buffer_too_small = 155,
  camellia_key_setup_failed = 157,
  cannot_get_parameters = 197,
  cannot_set_parameters = 198,
  cipher_not_gcm_mode = 184,
  cipher_parameter_error = 122,
  command_not_supported = 147,
  conflicting_algorithm_name = 201,
  copy_error = 173,
  ctrl_not_implemented = 132,
  ctrl_operation_not_implemented = 133,
  data_not_multiple_of_block_length = 138,
  decode_error = 114,
  different_key_types = 101,
  different_parameters = 153,
  error_loading_section = 165,
  error_setting_fips_mode = 166,
  expecting_an_hmac_key = 174,
  expecting_an_rsa_key = 127,
  expecting_a_dh_key = 128,
  expecting_a_dsa_key = 129,
  expecting_a_ec_key = 142,
  expecting_a_poly1305_key = 164,
  expecting_a_siphash_key = 175,
  fetch_failed = 202,
  final_error = 188,
  fips_mode_not_supported = 167,
  get_raw_key_failed = 182,
  illegal_scrypt_parameters = 171,
  inaccessible_domain_parameters = 204,
  inaccessible_key = 203,
  initialization_error = 134,
  input_not_initialized = 111,
  invalid_custom_length = 185,
  invalid_digest = 152,
  invalid_fips_mode = 168,
  invalid_iv_length = 194,
  invalid_key = 163,
  invalid_key_length = 130,
  invalid_operation = 148,
  invalid_provider_functions = 193,
  invalid_salt_length = 186,
  keygen_failure = 120,
  keymgmt_export_failure = 205,
  key_setup_failed = 180,
  memory_limit_exceeded = 172,
  message_digest_is_null = 159,
  method_not_supported = 144,
  missing_parameters = 103,
  not_able_to_copy_ctx = 190,
  not_xof_or_invalid_length = 178,
  no_cipher_set = 131,
  no_default_digest = 158,
  no_digest_set = 139,
  no_import_function = 206,
  no_keymgmt_available = 199,
  no_keymgmt_present = 196,
  no_key_set = 154,
  no_operation_set = 149,
  only_oneshot_supported = 177,
  operation_not_supported_for_this_keytype = 150,
  operaton_not_initialized = 151,
  parameter_too_large = 187,
  partially_overlapping = 162,
  pbkdf2_error = 181,
  pkey_application_asn1_method_already_registered = 179,
  private_key_decode_error = 145,
  private_key_encode_error = 146,
  public_key_not_rsa = 106,
  too_many_records = 183,
  unknown_cipher = 160,
  unknown_digest = 161,
  unknown_key_type = 207,
  unknown_option = 169,
  unknown_pbe_algorithm = 121,
  unsupported_algorithm = 156,
  unsupported_cipher = 107,
  unsupported_keylength = 123,
  unsupported_key_derivation_function = 124,
  unsupported_key_size = 108,
  unsupported_number_of_rounds = 135,
  unsupported_prf = 125,
  unsupported_private_key_algorithm = 118,
  unsupported_salt_type = 126,
  update_error = 189,
  wrap_mode_not_allowed = 170,
  wrong_final_block_length = 109,
  xts_data_unit_is_too_large = 191,
  xts_duplicated_keys = 192,
};

enum class engine {
  already_loaded = 100,
  argument_is_not_a_number = 133,
  cmd_not_executable = 134,
  command_takes_input = 135,
  command_takes_no_input = 136,
  conflicting_engine_id = 103,
  ctrl_command_not_implemented = 119,
  dso_failure = 104,
  dso_not_found = 132,
  engines_section_error = 148,
  engine_configuration_error = 102,
  engine_is_not_in_list = 105,
  engine_section_error = 149,
  failed_loading_private_key = 128,
  failed_loading_public_key = 129,
  finish_failed = 106,
  id_or_name_missing = 108,
  init_failed = 109,
  internal_list_error = 110,
  invalid_argument = 143,
  invalid_cmd_name = 137,
  invalid_cmd_number = 138,
  invalid_init_value = 151,
  invalid_string = 150,
  not_initialised = 117,
  not_loaded = 112,
  no_control_function = 120,
  no_index = 144,
  no_load_function = 125,
  no_reference = 130,
  no_such_engine = 116,
  unimplemented_cipher = 146,
  unimplemented_digest = 147,
  unimplemented_public_key_method = 101,
  version_incompatibility = 145,
};

enum class http {
  asn1_len_exceeds_max_resp_len = 108,
  connect_failure = 100,
  error_parsing_asn1_length = 109,
  error_parsing_content_length = 119,
  error_parsing_url = 101,
  error_receiving = 103,
  error_sending = 102,
  inconsistent_content_length = 120,
  max_resp_len_exceeded = 117,
  missing_asn1_encoding = 110,
  missing_content_type = 121,
  missing_redirect_location = 111,
  received_error = 105,
  received_wrong_http_version = 106,
  redirection_from_https_to_http = 112,
  redirection_not_enabled = 116,
  response_line_too_long = 113,
  response_parse_error = 104,
  sock_not_supported = 122,
  status_code_unsupported = 114,
  tls_not_enabled = 107,
  too_many_redirections = 115,
  unexpected_content_type = 118,
};

enum class io {
  accept = 100,
  addrinfo_address_is_not_af_inet = 141,
  ambiguous_host_or_service = 129,
  bad_fopen_mode = 101,
  broken_pipe = 124,
  connect_error = 103,
  connect_timeout = 147,
  gethostbyname_address_is_not_af_inet = 107,
  getsockname = 132,
  getsocketname_truncated_address = 133,
  getting_socktype = 134,
  invalid_argument = 125,
  invalid_socket = 135,
  in_use = 123,
  length_too_long = 102,
  listen_v6_only = 136,
  lookup_returned_nothing = 142,
  malformed_host_or_service = 130,
  nbio_connect_error = 110,
  no_accept_address_or_service_specified = 143,
  no_hostname_or_service_specified = 144,
  no_port_defined = 113,
  no_such_file = 128,
  null_parameter = 115,
  transfer_error = 104,
  transfer_timeout = 105,
  unable_to_bind_socket = 117,
  unable_to_create_socket = 118,
  unable_to_keepalive = 137,
  unable_to_listen_socket = 119,
  unable_to_nodelay = 138,
  unable_to_reuse_address = 139,
  unavailable_ip_family = 145,
  uninitialized = 120,
  unknown_info_type = 140,
  unsupported_ip_family = 146,
  unsupported_method = 121,
  unsupported_protocol_family = 131,
  write_to_read_only_bio = 126,
  wsastartup = 122,
};

enum class object {
  oid_exists = 102,
  unknown_nid = 101,
};

enum class ocsp {
  certificate_verify_error = 101,
  digest_err = 102,
  error_in_nextupdate_field = 122,
  error_in_thisupdate_field = 123,
  missing_ocspsigning_usage = 103,
  nextupdate_before_thisupdate = 124,
  not_basic_response = 104,
  no_certificates_in_chain = 105,
  no_response_data = 108,
  no_revoked_time = 109,
  no_signer_key = 130,
  private_key_does_not_match_certificate = 110,
  request_not_signed = 128,
  response_contains_no_revocation_data = 111,
  root_ca_not_trusted = 112,
  signature_failure = 117,
  signer_certificate_not_found = 118,
  status_expired = 125,
  status_not_yet_valid = 126,
  status_too_old = 127,
  unknown_message_digest = 119,
  unknown_nid = 120,
  unsupported_requestorname_type = 129,
};

enum class pkcs12 {
  cannot_pack_structure = 100,
  content_type_not_data = 121,
  decode = 101,
  encode = 102,
  encrypt = 103,
  error_setting_encrypted_data_type = 120,
  invalid_null_argument = 104,
  invalid_null_pkcs12_pointer = 105,
  iv_gen = 106,
  key_gen = 107,
  mac_absent = 108,
  mac_generation = 109,
  mac_setup = 110,
  mac_string_set = 111,
  mac_verify_failure = 113,
  parse = 114,
  algor_cipherinit = 115,
  cipherfinal = 116,
  pbe_crypt = 117,
  unknown_digest_algorithm = 118,
  unsupported_pkcs12_mode = 119,
};

enum class pkcs7 {
  certificate_verify_error = 117,
  cipher_has_no_object_identifier = 144,
  cipher_not_initialized = 116,
  content_and_data_present = 118,
  ctrl_error = 152,
  decrypt_error = 119,
  digest_failure = 101,
  encryption_ctrl_failure = 149,
  encryption_not_supported_for_this_key_type = 150,
  error_adding_recipient = 120,
  error_setting_cipher = 121,
  invalid_null_pointer = 143,
  invalid_signed_data_type = 155,
  no_content = 122,
  no_default_digest = 151,
  no_matching_digest_type_found = 154,
  no_recipient_matches_certificate = 115,
  no_signatures_on_data = 123,
  no_signers = 142,
  operation_not_supported_on_this_type = 104,
  pkcs7_add_signature_error = 124,
  pkcs7_add_signer_error = 153,
  pkcs7_datasign = 145,
  private_key_does_not_match_certificate = 127,
  signature_failure = 105,
  signer_certificate_not_found = 128,
  signing_ctrl_failure = 147,
  signing_not_supported_for_this_key_type = 148,
  smime_text_error = 129,
  unable_to_find_certificate = 106,
  unable_to_find_mem_bio = 107,
  unable_to_find_message_digest = 108,
  unknown_digest_type = 109,
  unknown_operation = 110,
  unsupported_cipher_type = 111,
  unsupported_content_type = 112,
  wrong_content_type = 113,
  wrong_pkcs7_type = 114,
};

enum class pem {
  bad_base64_decode = 100,
  bad_decrypt = 101,
  bad_end_line = 102,
  bad_iv_chars = 103,
  bad_magic_number = 116,
  bad_password_read = 104,
  bad_version_number = 117,
  bio_write_failure = 118,
  cipher_is_null = 127,
  error_converting_private_key = 115,
  expecting_private_key_blob = 119,
  expecting_public_key_blob = 120,
  header_too_long = 128,
  inconsistent_header = 121,
  keyblob_header_parse_error = 122,
  keyblob_too_short = 123,
  missing_dek_iv = 129,
  not_dek_info = 105,
  not_encrypted = 106,
  not_proc_type = 107,
  no_start_line = 108,
  problems_getting_password = 109,
  pvk_data_too_short = 124,
  pvk_too_short = 125,
  read_key = 111,
  short_header = 112,
  unexpected_dek_iv = 130,
  unsupported_cipher = 113,
  unsupported_encryption = 114,
  unsupported_key_components = 126,
};

enum class random {
  additional_input_too_long = 102,
  already_instantiated = 103,
  argument_out_of_range = 105,
  cannot_open_file = 121,
  derivation_function_mandatory_for_fips = 137,
  drbg_already_initialized = 129,
  drbg_not_initialised = 104,
  entropy_input_too_long = 106,
  entropy_out_of_range = 124,
  error_entropy_pool_was_ignored = 127,
  error_initialising_drbg = 107,
  error_instantiating_drbg = 108,
  error_retrieving_additional_input = 109,
  error_retrieving_entropy = 110,
  error_retrieving_nonce = 111,
  failed_to_create_lock = 126,
  func_not_implemented = 101,
  fwrite_error = 123,
  generate_error = 112,
  internal_error = 113,
  in_error_state = 114,
  not_a_regular_file = 122,
  not_instantiated = 115,
  no_drbg_implementation_selected = 128,
  parent_locking_not_enabled = 130,
  parent_strength_too_weak = 131,
  personalisation_string_too_long = 116,
  prediction_resistance_not_supported = 133,
  prng_not_seeded = 100,
  random_pool_overflow = 125,
  random_pool_underflow = 134,
  request_too_large_for_drbg = 117,
  reseed_error = 118,
  selftest_failure = 119,
  too_little_nonce_requested = 135,
  too_much_nonce_requested = 136,
  unsupported_drbg_flags = 132,
  unsupported_drbg_type = 120,
};

enum class rsa {
  algorithm_mismatch = 100,
  bad_e_value = 101,
  bad_fixed_header_decrypt = 102,
  bad_pad_byte_count = 103,
  bad_signature = 104,
  block_type_is_not_01 = 106,
  block_type_is_not_02 = 107,
  data_greater_than_mod_len = 108,
  data_too_large = 109,
  data_too_large_for_key_size = 110,
  data_too_large_for_modulus = 132,
  data_too_small = 111,
  data_too_small_for_key_size = 122,
  digest_does_not_match = 158,
  digest_not_allowed = 145,
  digest_too_big_for_rsa_key = 112,
  dmp1_not_congruent_to_d = 124,
  dmq1_not_congruent_to_d = 125,
  d_e_not_congruent_to_1 = 123,
  first_octet_invalid = 133,
  illegal_or_unsupported_padding_mode = 144,
  invalid_digest = 157,
  invalid_digest_length = 143,
  invalid_header = 137,
  invalid_keypair = 171,
  invalid_key_length = 173,
  invalid_label = 160,
  invalid_message_length = 131,
  invalid_mgf1_md = 156,
  invalid_modulus = 174,
  invalid_multi_prime_key = 167,
  invalid_oaep_parameters = 161,
  invalid_padding = 138,
  invalid_padding_mode = 141,
  invalid_pss_parameters = 149,
  invalid_pss_saltlen = 146,
  invalid_request = 175,
  invalid_salt_length = 150,
  invalid_strength = 176,
  invalid_trailer = 139,
  invalid_x931_digest = 142,
  iqmp_not_inverse_of_q = 126,
  key_prime_num_invalid = 165,
  key_size_too_small = 120,
  last_octet_invalid = 134,
  mgf1_digest_not_allowed = 152,
  missing_private_key = 179,
  modulus_too_large = 105,
  mp_coefficient_not_inverse_of_r = 168,
  mp_exponent_not_congruent_to_d = 169,
  mp_r_not_prime = 170,
  no_public_exponent = 140,
  null_before_block_missing = 113,
  n_does_not_equal_product_of_primes = 172,
  n_does_not_equal_p_q = 127,
  oaep_decoding_error = 121,
  operation_not_supported_for_this_keytype = 148,
  padding_check_failed = 114,
  pairwise_test_failure = 177,
  pkcs_decoding_error = 159,
  pss_saltlen_too_small = 164,
  pub_exponent_out_of_range = 178,
  p_not_prime = 128,
  q_not_prime = 129,
  rsa_operations_not_supported = 130,
  slen_check_failed = 136,
  slen_recovery_failed = 135,
  sslv3_rollback_attack = 115,
  the_asn1_object_identifier_is_not_known_for_this_md = 116,
  unknown_algorithm_type = 117,
  unknown_digest = 166,
  unknown_mask_digest = 151,
  unknown_padding_type = 118,
  unsupported_encryption_type = 162,
  unsupported_label_source = 163,
  unsupported_mask_algorithm = 153,
  unsupported_mask_parameter = 154,
  unsupported_signature_type = 155,
  value_missing = 147,
  wrong_signature_length = 119,
};

enum class store {
  ambiguous_content_type = 107,
  bad_password_read = 115,
  error_verifying_pkcs12_mac = 113,
  fingerprint_size_does_not_match_digest = 121,
  invalid_scheme = 106,
  is_not_a = 112,
  loader_incomplete = 116,
  loading_started = 117,
  not_a_certificate = 100,
  not_a_crl = 101,
  not_a_key = 102,
  not_a_name = 103,
  not_parameters = 104,
  passphrase_callback_error = 114,
  path_must_be_absolute = 108,
  search_only_supported_for_directories = 119,
  ui_process_interrupted_or_cancelled = 109,
  unregistered_scheme = 105,
  unsupported_content_type = 110,
  unsupported_operation = 118,
  unsupported_search_type = 120,
  uri_authority_unsupported = 111,
};

enum class ssl {
  application_data_after_close_notify = 291,
  app_data_in_handshake = 100,
  attempt_to_reuse_session_in_different_context = 272,
  at_least_tls_1_0_needed_in_fips_mode = 143,
  at_least_tls_1_2_needed_in_suiteb_mode = 158,
  bad_change_cipher_spec = 103,
  bad_cipher = 186,
  bad_data = 390,
  bad_data_returned_by_callback = 106,
  bad_decompression = 107,
  bad_dh_value = 102,
  bad_digest_length = 111,
  bad_early_data = 233,
  bad_ecc_cert = 304,
  bad_ecpoint = 306,
  bad_extension = 110,
  bad_handshake_length = 332,
  bad_handshake_state = 236,
  bad_hello_request = 105,
  bad_hrr_version = 263,
  bad_key_share = 108,
  bad_key_update = 122,
  bad_legacy_version = 292,
  bad_length = 271,
  bad_packet = 240,
  bad_packet_length = 115,
  bad_protocol_version_number = 116,
  bad_psk = 219,
  bad_psk_identity = 114,
  bad_record_type = 443,
  bad_rsa_encrypt = 119,
  bad_signature = 123,
  bad_srp_a_length = 347,
  bad_srp_parameters = 371,
  bad_srtp_mki_value = 352,
  bad_srtp_protection_profile_list = 353,
  bad_ssl_filetype = 124,
  bad_value = 384,
  bad_write_retry = 127,
  binder_does_not_verify = 253,
  bio_not_set = 128,
  block_cipher_pad_is_wrong = 129,
  bn_lib = 130,
  callback_failed = 234,
  cannot_change_cipher = 109,
  ca_dn_length_mismatch = 131,
  ca_key_too_small = 397,
  ca_md_too_weak = 398,
  ccs_received_early = 133,
  certificate_verify_failed = 134,
  cert_cb_error = 377,
  cert_length_mismatch = 135,
  ciphersuite_digest_has_changed = 218,
  cipher_code_wrong_length = 137,
  cipher_or_hash_unavailable = 138,
  clienthello_tlsext = 226,
  compressed_length_too_long = 140,
  compression_disabled = 343,
  compression_failure = 141,
  compression_id_not_within_private_range = 307,
  compression_library_error = 142,
  connection_type_not_set = 144,
  context_not_dane_enabled = 167,
  cookie_gen_callback_failure = 400,
  cookie_mismatch = 308,
  custom_ext_handler_already_installed = 206,
  dane_already_enabled = 172,
  dane_cannot_override_mtype_full = 173,
  dane_not_enabled = 175,
  dane_tlsa_bad_certificate = 180,
  dane_tlsa_bad_certificate_usage = 184,
  dane_tlsa_bad_data_length = 189,
  dane_tlsa_bad_digest_length = 192,
  dane_tlsa_bad_matching_type = 200,
  dane_tlsa_bad_public_key = 201,
  dane_tlsa_bad_selector = 202,
  dane_tlsa_null_data = 203,
  data_between_ccs_and_finished = 145,
  data_length_too_long = 146,
  decryption_failed = 147,
  decryption_failed_or_bad_record_mac = 281,
  dh_key_too_small = 394,
  dh_public_value_length_is_wrong = 148,
  digest_check_failed = 149,
  dtls_message_too_big = 334,
  duplicate_compression_id = 309,
  ecc_cert_not_for_signing = 318,
  ecdh_required_for_suiteb_mode = 374,
  ee_key_too_small = 399,
  empty_srtp_protection_profile_list = 354,
  encrypted_length_too_long = 150,
  error_in_received_cipher_list = 151,
  error_setting_tlsa_base_domain = 204,
  exceeds_max_fragment_size = 194,
  excessive_message_size = 152,
  extension_not_received = 279,
  extra_data_in_message = 153,
  ext_length_mismatch = 163,
  failed_to_init_async = 405,
  algorithm_fetch_failed = 295,
  fragmented_client_hello = 401,
  got_a_fin_before_a_ccs = 154,
  https_proxy_request = 155,
  http_request = 156,
  illegal_point_compression = 162,
  illegal_suiteb_digest = 380,
  inappropriate_fallback = 373,
  inconsistent_compression = 340,
  inconsistent_early_data_alpn = 222,
  inconsistent_early_data_sni = 231,
  inconsistent_extms = 104,
  insufficient_security = 241,
  invalid_alert = 205,
  invalid_ccs_message = 260,
  invalid_certificate_or_alg = 238,
  invalid_command = 280,
  invalid_compression_algorithm = 341,
  invalid_config = 283,
  invalid_configuration_name = 113,
  invalid_context = 282,
  invalid_ct_validation_type = 212,
  invalid_key_update_type = 120,
  invalid_max_early_data = 174,
  invalid_null_cmd_name = 385,
  invalid_sequence_number = 402,
  invalid_serverinfo_data = 388,
  invalid_session_id = 999,
  invalid_srp_username = 357,
  invalid_status_response = 328,
  invalid_ticket_keys_length = 325,
  length_mismatch = 159,
  length_too_long = 404,
  length_too_short = 160,
  library_bug = 274,
  library_has_no_ciphers = 161,
  missing_dsa_signing_cert = 165,
  missing_ecdsa_signing_cert = 381,
  missing_fatal = 256,
  missing_parameters = 290,
  missing_rsa_certificate = 168,
  missing_rsa_encrypting_cert = 169,
  missing_rsa_signing_cert = 170,
  missing_sigalgs_extension = 112,
  missing_signing_cert = 221,
  missing_srp_param = 358,
  missing_supported_groups_extension = 209,
  missing_tmp_dh_key = 171,
  missing_tmp_ecdh_key = 311,
  mixed_handshake_and_non_handshake_data = 293,
  not_on_record_boundary = 182,
  not_replacing_certificate = 289,
  not_server = 284,
  no_application_protocol = 235,
  no_certificates_returned = 176,
  no_certificate_assigned = 177,
  no_certificate_set = 179,
  no_change_following_hrr = 214,
  no_ciphers_available = 181,
  no_ciphers_specified = 183,
  no_cipher_match = 185,
  no_client_cert_method = 331,
  no_compression_specified = 187,
  no_cookie_callback_set = 287,
  no_gost_certificate_sent_by_peer = 330,
  no_method_specified = 188,
  no_pem_extensions = 389,
  no_private_key_assigned = 190,
  no_protocols_available = 191,
  no_renegotiation = 339,
  no_required_digest = 324,
  no_shared_cipher = 193,
  no_shared_groups = 410,
  no_shared_signature_algorithms = 376,
  no_srtp_profiles = 359,
  no_suitable_key_share = 101,
  no_suitable_signature_algorithm = 118,
  no_valid_scts = 216,
  no_verify_cookie_callback = 403,
  null_ssl_ctx = 195,
  null_ssl_method_passed = 196,
  old_session_cipher_not_returned = 197,
  old_session_compression_algorithm_not_returned = 344,
  overflow_error = 237,
  packet_length_too_long = 198,
  parse_tlsext = 227,
  path_too_long = 270,
  peer_did_not_return_a_certificate = 199,
  pem_name_bad_prefix = 391,
  pem_name_too_short = 392,
  pipeline_failure = 406,
  post_handshake_auth_encoding_err = 278,
  private_key_mismatch = 288,
  protocol_is_shutdown = 207,
  psk_identity_not_found = 223,
  psk_no_client_cb = 224,
  psk_no_server_cb = 225,
  read_bio_not_set = 211,
  read_timeout_expired = 312,
  record_length_mismatch = 213,
  record_too_small = 298,
  renegotiate_ext_too_long = 335,
  renegotiation_encoding_err = 336,
  renegotiation_mismatch = 337,
  request_pending = 285,
  request_sent = 286,
  required_cipher_missing = 215,
  required_compression_algorithm_missing = 342,
  scsv_received_when_renegotiating = 345,
  sct_verification_failed = 208,
  serverhello_tlsext = 275,
  session_id_context_uninitialized = 277,
  shutdown_while_in_init = 407,
  signature_algorithms_error = 360,
  signature_for_non_signing_certificate = 220,
  srp_a_calc = 361,
  srtp_could_not_allocate_profiles = 362,
  srtp_protection_profile_list_too_long = 363,
  srtp_unknown_protection_profile = 364,
  ssl3_ext_invalid_max_fragment_length = 232,
  ssl3_ext_invalid_servername = 319,
  ssl3_ext_invalid_servername_type = 320,
  ssl3_session_id_too_long = 300,
  sslv3_alert_bad_certificate = 1042,
  sslv3_alert_bad_record_mac = 1020,
  sslv3_alert_certificate_expired = 1045,
  sslv3_alert_certificate_revoked = 1044,
  sslv3_alert_certificate_unknown = 1046,
  sslv3_alert_decompression_failure = 1030,
  sslv3_alert_handshake_failure = 1040,
  sslv3_alert_illegal_parameter = 1047,
  sslv3_alert_no_certificate = 1041,
  sslv3_alert_unexpected_message = 1010,
  sslv3_alert_unsupported_certificate = 1043,
  ssl_command_section_empty = 117,
  ssl_command_section_not_found = 125,
  ssl_ctx_has_no_default_ssl_version = 228,
  ssl_handshake_failure = 229,
  ssl_library_has_no_ciphers = 230,
  ssl_negative_length = 372,
  ssl_section_empty = 126,
  ssl_section_not_found = 136,
  ssl_session_id_callback_failed = 301,
  ssl_session_id_conflict = 302,
  ssl_session_id_context_too_long = 273,
  ssl_session_id_has_bad_length = 303,
  ssl_session_id_too_long = 408,
  ssl_session_version_mismatch = 210,
  still_in_init = 121,
  tlsv13_alert_certificate_required = 1116,
  tlsv13_alert_missing_extension = 1109,
  tlsv1_alert_access_denied = 1049,
  tlsv1_alert_decode_error = 1050,
  tlsv1_alert_decryption_failed = 1021,
  tlsv1_alert_decrypt_error = 1051,
  tlsv1_alert_export_restriction = 1060,
  tlsv1_alert_inappropriate_fallback = 1086,
  tlsv1_alert_insufficient_security = 1071,
  tlsv1_alert_internal_error = 1080,
  tlsv1_alert_no_renegotiation = 1100,
  tlsv1_alert_protocol_version = 1070,
  tlsv1_alert_record_overflow = 1022,
  tlsv1_alert_unknown_ca = 1048,
  tlsv1_alert_user_cancelled = 1090,
  tlsv1_bad_certificate_hash_value = 1114,
  tlsv1_bad_certificate_status_response = 1113,
  tlsv1_certificate_unobtainable = 1111,
  tlsv1_unrecognized_name = 1112,
  tlsv1_unsupported_extension = 1110,
  tls_illegal_exporter_label = 367,
  tls_invalid_ecpointformat_list = 157,
  too_many_key_updates = 132,
  too_many_warn_alerts = 409,
  too_much_early_data = 164,
  unable_to_find_ecdh_parameters = 314,
  unable_to_find_public_key_parameters = 239,
  unable_to_load_ssl3_md5_routines = 242,
  unable_to_load_ssl3_sha1_routines = 243,
  unexpected_ccs_message = 262,
  unexpected_end_of_early_data = 178,
  unexpected_eof_while_reading = 294,
  unexpected_message = 244,
  unexpected_record = 245,
  uninitialized = 276,
  unknown_alert_type = 246,
  unknown_certificate_type = 247,
  unknown_cipher_returned = 248,
  unknown_cipher_type = 249,
  unknown_cmd_name = 386,
  unknown_command = 139,
  unknown_digest = 368,
  unknown_key_exchange_type = 250,
  unknown_pkey_type = 251,
  unknown_protocol = 252,
  unknown_ssl_version = 254,
  unknown_state = 255,
  unsafe_legacy_renegotiation_disabled = 338,
  unsolicited_extension = 217,
  unsupported_compression_algorithm = 257,
  unsupported_elliptic_curve = 315,
  unsupported_protocol = 258,
  unsupported_ssl_version = 259,
  unsupported_status_type = 329,
  use_srtp_not_negotiated = 369,
  version_too_high = 166,
  version_too_low = 396,
  wrong_certificate_type = 383,
  wrong_cipher_returned = 261,
  wrong_curve = 378,
  wrong_signature_length = 264,
  wrong_signature_size = 265,
  wrong_signature_type = 370,
  wrong_ssl_version = 266,
  wrong_version_number = 267,
  x509_lib = 268,
  x509_verification_setup_problems = 269,
};

enum class ts {
  bad_pkcs7_type = 132,
  bad_type = 133,
  cannot_load_cert = 137,
  cannot_load_key = 138,
  certificate_verify_error = 100,
  could_not_set_engine = 127,
  could_not_set_time = 115,
  detached_content = 134,
  ess_add_signing_cert_error = 116,
  ess_add_signing_cert_v2_error = 139,
  ess_signing_certificate_error = 101,
  invalid_null_pointer = 102,
  invalid_signer_certificate_purpose = 117,
  message_imprint_mismatch = 103,
  nonce_mismatch = 104,
  nonce_not_returned = 105,
  no_content = 106,
  no_time_stamp_token = 107,
  pkcs7_add_signature_error = 118,
  pkcs7_add_signed_attr_error = 119,
  pkcs7_to_ts_tst_info_failed = 129,
  policy_mismatch = 108,
  private_key_does_not_match_certificate = 120,
  response_setup_error = 121,
  signature_failure = 109,
  there_must_be_one_signer = 110,
  time_syscall_error = 122,
  token_not_present = 130,
  token_present = 131,
  tsa_name_mismatch = 111,
  tsa_untrusted = 112,
  tst_info_setup_error = 123,
  ts_datasign = 124,
  unacceptable_policy = 125,
  unsupported_md_algorithm = 126,
  unsupported_version = 113,
  var_bad_value = 135,
  var_lookup_failure = 136,
  wrong_content_type = 114,
};

enum class ui {
  common_ok_and_cancel_characters = 104,
  index_too_large = 102,
  index_too_small = 103,
  no_result_buffer = 105,
  processing_error = 107,
  result_too_large = 100,
  result_too_small = 101,
  sysassign_error = 109,
  sysdassgn_error = 110,
  sysqiow_error = 111,
  unknown_control_command = 106,
  unknown_ttyget_errno_value = 108,
  user_data_duplication_unsupported = 112,
};

enum class x509v3 {
  bad_ip_address = 118,
  bad_object = 119,
  bn_dec2bn_error = 100,
  bn_to_asn1_integer_error = 101,
  dirname_error = 149,
  distpoint_already_set = 160,
  duplicate_zone_id = 133,
  error_converting_zone = 131,
  error_creating_extension = 144,
  error_in_extension = 128,
  expected_a_section_name = 137,
  extension_exists = 145,
  extension_name_error = 115,
  extension_not_found = 102,
  extension_setting_not_supported = 103,
  extension_value_error = 116,
  illegal_empty_extension = 151,
  incorrect_policy_syntax_tag = 152,
  invalid_asnumber = 162,
  invalid_asrange = 163,
  invalid_boolean_string = 104,
  invalid_extension_string = 105,
  invalid_inheritance = 165,
  invalid_ipaddress = 166,
  invalid_multiple_rdns = 161,
  invalid_name = 106,
  invalid_null_argument = 107,
  invalid_null_name = 108,
  invalid_null_value = 109,
  invalid_number = 140,
  invalid_numbers = 141,
  invalid_object_identifier = 110,
  invalid_option = 138,
  invalid_policy_identifier = 134,
  invalid_proxy_policy_setting = 153,
  invalid_purpose = 146,
  invalid_safi = 164,
  invalid_section = 135,
  invalid_syntax = 143,
  issuer_decode_error = 126,
  missing_value = 124,
  need_organization_and_numbers = 142,
  no_config_database = 136,
  no_issuer_certificate = 121,
  no_issuer_details = 127,
  no_policy_identifier = 139,
  no_proxy_cert_policy_language_defined = 154,
  no_public_key = 114,
  no_subject_details = 125,
  operation_not_defined = 148,
  othername_error = 147,
  policy_language_already_defined = 155,
  policy_path_length = 156,
  policy_path_length_already_defined = 157,
  policy_when_proxy_language_requires_no_policy = 159,
  section_not_found = 150,
  unable_to_get_issuer_details = 122,
  unable_to_get_issuer_keyid = 123,
  unknown_bit_string_argument = 111,
  unknown_extension = 129,
  unknown_extension_name = 130,
  unknown_option = 120,
  unsupported_option = 117,
  unsupported_type = 167,
  user_too_long = 132,
};

enum class x509 {
  akid_mismatch = 110,
  bad_selector = 133,
  bad_x509_filetype = 100,
  base64_decode_error = 118,
  cant_check_dh_key = 114,
  cert_already_in_hash_table = 101,
  certificate_verification_failed = 139,
  crl_already_delta = 127,
  crl_verify_failure = 131,
  idp_mismatch = 128,
  invalid_attributes = 138,
  invalid_directory = 113,
  invalid_field_name = 119,
  invalid_trust = 123,
  issuer_mismatch = 129,
  key_type_mismatch = 115,
  key_values_mismatch = 116,
  loading_cert_dir = 103,
  loading_defaults = 104,
  method_not_supported = 124,
  name_too_long = 134,
  newer_crl_not_newer = 132,
  no_certificate_found = 135,
  no_certificate_or_crl_found = 136,
  no_cert_set_for_us_to_verify = 105,
  no_crl_found = 137,
  no_crl_number = 130,
  public_key_decode_error = 125,
  public_key_encode_error = 126,
  should_retry = 106,
  unable_to_find_parameters_in_chain = 107,
  unable_to_get_certs_public_key = 108,
  unknown_key_type = 117,
  unknown_nid = 109,
  unknown_purpose_id = 121,
  unknown_trust_id = 120,
  unsupported_algorithm = 111,
  wrong_lookup_type = 112,
  wrong_type = 122,
};

} /* namespace aegis */

/* is_error_code_enum specializations */
namespace std {

template <>
struct is_error_code_enum<::aegis::error::async> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::asn1> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::bignum> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::certificate_management_protocol> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::cryptographic_message_syntax> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::certificate_transparency> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::configuration> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::compression> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::crypto> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::diffie_hellman> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::dsa> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::enhanced_security_service> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::elliptic_curve> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::envelope> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::engine> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::http> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::io> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::object> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::ocsp> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::pkcs12> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::pkcs7> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::pem> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::random> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::rsa> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::store> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::ssl> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::ts> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::ui> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::x509v3> :
  true_type
{ };

template <>
struct is_error_code_enum<::aegis::error::x509> :
  true_type
{ };

} /* namespace std */

#endif /* AEGIS_ERROR_HPP */
