#ifndef AEGIS_ERROR_HPP
#define AEGIS_ERROR_HPP

#include <system_error>

namespace aegis::category {

::std::error_category const& async () noexcept;
::std::error_category const& asn1 () noexcept;

::std::error_category const& bignum () noexcept;

::std::error_category const& certificate_management_protocol () noexcept; // CMP_*
::std::error_category const& cryptographic_message_syntax () noexcept; // CMS_*
::std::error_category const& certificate_transparency () noexcept; // CT_*
::std::error_category const& configuration () noexcept;
::std::error_category const& compression () noexcept;
::std::error_category const& crypto () noexcept;

::std::error_category const& diffie_hellman () noexcept;
::std::error_category const& dsa () noexcept;

::std::error_category const& enhanced_security_service () noexcept; // ess
::std::error_category const& elliptic_curve () noexcept;
::std::error_category const& envelope () noexcept; // evp
::std::error_category const& engine () noexcept;

::std::error_category const& generic () noexcept;

::std::error_category const& http () noexcept;

::std::error_category const& io () noexcept;

::std::error_category const& key_derivation () noexcept; // kdf

::std::error_category const& object () noexcept; // asn1 objects
::std::error_category const& ocsp () noexcept;

::std::error_category const& pkcs12 () noexcept;
::std::error_category const& pkcs7 () noexcept;
::std::error_category const& pem () noexcept;

::std::error_category const& random () noexcept;
::std::error_category const& rsa () noexcept;

::std::error_category const& store () noexcept;
::std::error_category const& ssl () noexcept;

::std::error_category const& ts () noexcept; // asn1 ts

::std::error_category const& ui () noexcept;

::std::error_category const& x509v3 () noexcept;
::std::error_category const& x509 () noexcept;

} /* namespace aegis */

namespace aegis::error {

enum class async {
  failed_to_set_pool = 101,
  failed_to_swap_context = 102,
  init_failed = 105,
  invalid_pool_size = 103,
};

enum class asn1 {
  adding_object = 171,
  asn1_parse_error = 203,
  asn1_sig_parse_error = 204,
  aux_error = 100,
  bad_object_header = 102,
  bmpstring_is_wrong_length = 214,
  bn_lib = 105,
  boolean_is_wrong_length = 106,
  buffer_too_small = 107,
  cipher_has_no_object_identifier = 108,
  context_not_initialised = 217,
  data_is_wrong = 109,
  decode_error = 110,
  depth_exceeded = 174,
  digest_and_key_type_not_supported = 198,
  encode_error = 112,
  error_getting_time = 173,
  error_loading_section = 172,
  error_setting_cipher_params = 114,
  expecting_an_integer = 115,
  expecting_an_object = 116,
  explicit_length_mismatch = 119,
  explicit_tag_not_constructed = 120,
  field_missing = 121,
  first_num_too_large = 122,
  header_too_long = 123,
  illegal_bitstring_format = 175,
  illegal_boolean = 176,
  illegal_characters = 124,
  illegal_format = 177,
  illegal_hex = 178,
  illegal_implicit_tag = 179,
  illegal_integer = 180,
  illegal_negative_value = 226,
  illegal_nested_tagging = 181,
  illegal_null = 125,
  illegal_null_value = 182,
  illegal_object = 183,
  illegal_optional_any = 126,
  illegal_options_on_item_template = 170,
  illegal_padding = 221,
  illegal_tagged_any = 127,
  illegal_time_value = 184,
  illegal_zero_content = 222,
  integer_not_ascii_format = 185,
  integer_too_large_for_long = 128,
  invalid_bit_string_bits_left = 220,
  invalid_bmpstring_length = 129,
  invalid_digit = 130,
  invalid_mime_type = 205,
  invalid_modifier = 186,
  invalid_number = 187,
  invalid_object_encoding = 216,
  invalid_scrypt_parameters = 227,
  invalid_separator = 131,
  invalid_string_table_value = 218,
  invalid_universalstring_length = 133,
  invalid_utf8string = 134,
  invalid_value = 219,
  list_error = 188,
  mime_no_content_type = 206,
  mime_parse_error = 207,
  mime_sig_parse_error = 208,
  missing_eoc = 137,
  missing_second_number = 138,
  missing_value = 189,
  mstring_not_universal = 139,
  mstring_wrong_tag = 140,
  nested_asn1_string = 197,
  nested_too_deep = 201,
  non_hex_characters = 141,
  not_ascii_format = 190,
  not_enough_data = 142,
  no_content_type = 209,
  no_matching_choice_type = 143,
  no_multipart_body_failure = 210,
  no_multipart_boundary = 211,
  no_sig_content_type = 212,
  null_is_wrong_length = 144,
  object_not_ascii_format = 191,
  odd_number_of_chars = 145,
  second_number_too_large = 147,
  sequence_length_mismatch = 148,
  sequence_not_constructed = 149,
  sequence_or_set_needs_config = 192,
  short_line = 150,
  sig_invalid_mime_type = 213,
  streaming_not_supported = 202,
  string_too_long = 151,
  string_too_short = 152,
  the_asn1_object_identifier_is_not_known_for_this_md = 154,
  time_not_ascii_format = 193,
  too_large = 223,
  too_long = 155,
  too_small = 224,
  type_not_constructed = 156,
  type_not_primitive = 195,
  unexpected_eoc = 159,
  universalstring_is_wrong_length = 215,
  unknown_format = 160,
  unknown_message_digest_algorithm = 161,
  unknown_object_type = 162,
  unknown_public_key_type = 163,
  unknown_signature_algorithm = 199,
  unknown_tag = 194,
  unsupported_any_defined_by_type = 164,
  unsupported_cipher = 228,
  unsupported_public_key_type = 167,
  unsupported_type = 196,
  wrong_integer_type = 225,
  wrong_public_key_type = 200,
  wrong_tag = 168,
};

enum class bignum {
  arg2_lt_arg3 = 100,
  bad_reciprocal = 101,
  bignum_too_long = 114,
  bits_too_small = 118,
  called_with_even_modulus = 102,
  divide_by_zero = 103,
  encoding_error = 104,
  expand_on_static_bignum_data = 105,
  input_not_reduced = 110,
  invalid_length = 106,
  invalid_range = 115,
  invalid_shift = 119,
  not_a_square = 111,
  not_initialized = 107,
  no_inverse = 108,
  no_solution = 116,
  no_suitable_digest = 120,
  private_key_too_large = 117,
  p_is_not_prime = 112,
  too_many_iterations = 113,
  too_many_temporary_variables = 109,
};

enum class certificate_management_protocol {
  algorithm_not_supported = 139,
  bad_checkafter_in_pollrep = 167,
  bad_request_id = 108,
  certhash_unmatched = 156,
  certid_not_found = 109,
  certificate_not_accepted = 169,
  certificate_not_found = 112,
  certreqmsg_not_found = 157,
  certresponse_not_found = 113,
  cert_and_key_do_not_match = 114,
  checkafter_out_of_range = 181,
  checking_pbm_no_secret_available = 166,
  encountered_keyupdatewarning = 176,
  encountered_waiting = 162,
  error_calculating_protection = 115,
  error_creating_certconf = 116,
  error_creating_certrep = 117,
  error_creating_cr = 163,
  error_creating_error = 118,
  error_creating_genm = 119,
  error_creating_genp = 120,
  error_creating_ir = 164,
  error_creating_kur = 165,
  error_creating_p10cr = 121,
  error_creating_pkiconf = 122,
  error_creating_pollrep = 123,
  error_creating_pollreq = 124,
  error_creating_rp = 125,
  error_creating_rr = 126,
  error_parsing_pkistatus = 107,
  error_processing_message = 158,
  error_protecting_message = 127,
  error_setting_certhash = 128,
  error_unexpected_certconf = 160,
  error_validating_protection = 140,
  failed_extracting_pubkey = 141,
  failure_obtaining_random = 110,
  fail_info_out_of_range = 129,
  invalid_args = 100,
  missing_key_input_for_creating_protection = 130,
  missing_key_usage_digitalsignature = 142,
  missing_private_key = 131,
  missing_protection = 143,
  missing_reference_cert = 168,
  missing_sender_identification = 111,
  missing_trust_store = 144,
  multiple_requests_not_supported = 161,
  multiple_responses_not_supported = 170,
  multiple_san_sources = 102,
  no_stdio = 194,
  no_suitable_sender_cert = 145,
  null_argument = 103,
  pkibody_error = 146,
  pkistatusinfo_not_found = 132,
  polling_failed = 172,
  potentially_invalid_certificate = 147,
  received_error = 180,
  recipnonce_unmatched = 148,
  request_not_accepted = 149,
  request_rejected_by_server = 182,
  sender_generalname_type_not_supported = 150,
  srvcert_does_not_validate_msg = 151,
  total_timeout = 184,
  transactionid_unmatched = 152,
  transfer_error = 159,
  unexpected_pkibody = 133,
  unexpected_pkistatus = 185,
  unexpected_pvno = 153,
  unknown_algorithm_id = 134,
  unknown_cert_type = 135,
  unknown_pkistatus = 186,
  unsupported_algorithm = 136,
  unsupported_key_type = 137,
  unsupported_protection_alg_dhbasedmac = 154,
  wrong_algorithm_oid = 138,
  wrong_certid_in_rp = 187,
  wrong_pbm_value = 155,
  wrong_rp_component_count = 188,
  wrong_serial_in_rp = 173,
};

enum class cryptographic_message_syntax {
  add_signer_error = 99,
  attribute_error = 161,
  certificate_already_present = 175,
  certificate_has_no_keyid = 160,
  certificate_verify_error = 100,
  cipher_initialisation_error = 101,
  cipher_parameter_initialisation_error = 102,
  cms_datafinal_error = 103,
  cms_lib = 104,
  contentidentifier_mismatch = 170,
  content_not_found = 105,
  content_type_mismatch = 171,
  content_type_not_compressed_data = 106,
  content_type_not_enveloped_data = 107,
  content_type_not_signed_data = 108,
  content_verify_error = 109,
  ctrl_error = 110,
  ctrl_failure = 111,
  decrypt_error = 112,
  error_getting_public_key = 113,
  error_reading_messagedigest_attribute = 114,
  error_setting_key = 115,
  error_setting_recipientinfo = 116,
  invalid_encrypted_key_length = 117,
  invalid_key_encryption_parameter = 176,
  invalid_key_length = 118,
  md_bio_init_error = 119,
  messagedigest_attribute_wrong_length = 120,
  messagedigest_wrong_length = 121,
  msgsigdigest_error = 172,
  msgsigdigest_verification_failure = 162,
  msgsigdigest_wrong_length = 163,
  need_one_signer = 164,
  not_a_signed_receipt = 165,
  not_encrypted_data = 122,
  not_kek = 123,
  not_key_agreement = 181,
  not_key_transport = 124,
  not_pwri = 177,
  not_supported_for_this_key_type = 125,
  no_cipher = 126,
  no_content = 127,
  no_content_type = 173,
  no_default_digest = 128,
  no_digest_set = 129,
  no_key = 130,
  no_key_or_cert = 174,
  no_matching_digest = 131,
  no_matching_recipient = 132,
  no_matching_signature = 166,
  no_msgsigdigest = 167,
  no_password = 178,
  no_private_key = 133,
  no_public_key = 134,
  no_receipt_request = 168,
  no_signers = 135,
  private_key_does_not_match_certificate = 136,
  receipt_decode_error = 169,
  recipient_error = 137,
  signer_certificate_not_found = 138,
  signfinal_error = 139,
  smime_text_error = 140,
  store_init_error = 141,
  type_not_compressed_data = 142,
  type_not_data = 143,
  type_not_digested_data = 144,
  type_not_encrypted_data = 145,
  type_not_enveloped_data = 146,
  unable_to_finalize_context = 147,
  unknown_cipher = 148,
  unknown_digest_algorithm = 149,
  unknown_id = 150,
  unsupported_compression_algorithm = 151,
  unsupported_content_type = 152,
  unsupported_kek_algorithm = 153,
  unsupported_key_encryption_algorithm = 179,
  unsupported_recipientinfo_type = 155,
  unsupported_recipient_type = 154,
  unsupported_type = 156,
  unwrap_error = 157,
  unwrap_failure = 180,
  verification_failure = 158,
  wrap_error = 159,
};

enum class certificate_transparency {
  base64_decode_error = 108,
  invalid_log_id_length = 100,
  log_conf_invalid = 109,
  log_conf_invalid_key = 110,
  log_conf_missing_description = 111,
  log_conf_missing_key = 112,
  log_key_invalid = 113,
  sct_future_timestamp = 116,
  sct_invalid = 104,
  sct_invalid_signature = 107,
  sct_list_invalid = 105,
  sct_log_id_mismatch = 114,
  sct_not_set = 106,
  sct_unsupported_version = 115,
  unrecognized_signature_nid = 101,
  unsupported_entry_type = 102,
  unsupported_version = 103,
};

enum class configuration {
  error_loading_dso = 110,
  invalid_pragma = 122,
  list_cannot_be_null = 115,
  mandatory_braces_in_variable_expansion = 123,
  missing_close_square_bracket = 100,
  missing_equal_sign = 101,
  missing_init_function = 112,
  module_initialization_error = 109,
  no_close_brace = 102,
  no_conf = 105,
  no_conf_or_environment_variable = 106,
  no_section = 107,
  no_such_file = 114,
  no_value = 108,
  number_too_large = 121,
  recursive_directory_include = 111,
  ssl_command_section_empty = 117,
  ssl_command_section_not_found = 118,
  ssl_section_empty = 119,
  ssl_section_not_found = 120,
  unable_to_create_new_section = 103,
  unknown_module_name = 113,
  variable_expansion_too_long = 116,
  variable_has_no_value = 104,
};

enum class compression {
  zlib_deflate_error = 99,
  zlib_inflate_error = 100,
  zlib_not_supported = 101,
};

enum class crypto {
  bad_algorithm_name = 117,
  conflicting_names = 118,
  fips_mode_not_supported = 101,
  illegal_hex_digit = 102,
  insufficient_data_space = 106,
  insufficient_param_size = 107,
  insufficient_secure_data_space = 108,
  invalid_null_argument = 109,
  invalid_ossl_param_type = 110,
  odd_number_of_digits = 103,
  provider_already_exists = 104,
  provider_section_error = 105,
  secure_malloc_failure = 111,
  string_too_long = 112,
  too_many_bytes = 113,
  too_many_records = 114,
  too_small_buffer = 116,
  zero_length_number = 115,
};

enum class diffie_hellman {
  bad_generator = 101,
  bn_decode_error = 109,
  bn_error = 106,
  check_invalid_j_value = 115,
  check_invalid_q_value = 116,
  check_pubkey_invalid = 122,
  check_pubkey_too_large = 123,
  check_pubkey_too_small = 124,
  check_p_not_prime = 117,
  check_p_not_safe_prime = 118,
  check_q_not_prime = 119,
  decode_error = 104,
  invalid_parameter_name = 110,
  invalid_parameter_nid = 114,
  invalid_pubkey = 102,
  kdf_parameter_error = 112,
  keys_not_set = 108,
  missing_pubkey = 125,
  modulus_too_large = 103,
  modulus_too_small = 126,
  not_suitable_generator = 120,
  no_parameters_set = 107,
  no_private_value = 100,
  parameter_encoding_error = 105,
  peer_key_error = 111,
  shared_info_error = 113,
  unable_to_check_generator = 121,
};

enum class dsa {
  bad_q_value = 102,
  bn_decode_error = 108,
  bn_error = 109,
  decode_error = 104,
  invalid_digest_type = 106,
  invalid_parameters = 112,
  missing_parameters = 101,
  missing_private_key = 111,
  modulus_too_large = 103,
  no_parameters_set = 107,
  parameter_encoding_error = 105,
  q_not_prime = 113,
  seed_len_small = 110,
};

enum class enhanced_security_service {
  signing_certificate_error = 102,
  signing_cert_add_error = 100,
  signing_cert_v2_add_error = 101,
};

enum class elliptic_curve {
  asn1_error = 115,
  bad_signature = 156,
  bignum_out_of_range = 144,
  buffer_too_small = 100,
  cannot_invert = 165,
  coordinates_out_of_range = 146,
  curve_does_not_support_ecdh = 160,
  curve_does_not_support_ecdsa = 170,
  curve_does_not_support_signing = 159,
  d2i_ecpkparameters_failure = 117,
  decode_error = 142,
  discriminant_is_zero = 118,
  ec_group_new_by_name_failure = 119,
  failed_making_public_key = 166,
  field_too_large = 143,
  gf2m_not_supported = 147,
  group2pkparameters_failure = 120,
  i2d_ecpkparameters_failure = 121,
  incompatible_objects = 101,
  invalid_argument = 112,
  invalid_compressed_point = 110,
  invalid_compression_bit = 109,
  invalid_curve = 141,
  invalid_digest = 151,
  invalid_digest_type = 138,
  invalid_encoding = 102,
  invalid_field = 103,
  invalid_form = 104,
  invalid_group_order = 122,
  invalid_key = 116,
  invalid_output_length = 161,
  invalid_peer_key = 133,
  invalid_pentanomial_basis = 132,
  invalid_private_key = 123,
  invalid_trinomial_basis = 137,
  kdf_parameter_error = 148,
  keys_not_set = 140,
  ladder_post_failure = 136,
  ladder_pre_failure = 153,
  ladder_step_failure = 162,
  missing_parameters = 124,
  missing_private_key = 125,
  need_new_setup_values = 157,
  not_a_nist_prime = 135,
  not_implemented = 126,
  not_initialized = 111,
  no_parameters_set = 139,
  no_private_value = 154,
  operation_not_supported = 152,
  passed_null_parameter = 134,
  peer_key_error = 149,
  pkparameters2group_failure = 127,
  point_arithmetic_failure = 155,
  point_at_infinity = 106,
  point_coordinates_blind_failure = 163,
  point_is_not_on_curve = 107,
  random_number_generation_failed = 158,
  shared_info_error = 150,
  slot_full = 108,
  undefined_generator = 113,
  undefined_order = 128,
  unknown_cofactor = 164,
  unknown_group = 129,
  unknown_order = 114,
  unsupported_field = 131,
  wrong_curve_parameters = 145,
  wrong_order = 130,
};

enum class envelope {
  aes_key_setup_failed = 143,
  aria_key_setup_failed = 176,
  bad_algorithm_name = 200,
  bad_decrypt = 100,
  bad_key_length = 195,
  buffer_too_small = 155,
  camellia_key_setup_failed = 157,
  cannot_get_parameters = 197,
  cannot_set_parameters = 198,
  cipher_not_gcm_mode = 184,
  cipher_parameter_error = 122,
  command_not_supported = 147,
  conflicting_algorithm_name = 201,
  copy_error = 173,
  ctrl_not_implemented = 132,
  ctrl_operation_not_implemented = 133,
  data_not_multiple_of_block_length = 138,
  decode_error = 114,
  different_key_types = 101,
  different_parameters = 153,
  error_loading_section = 165,
  error_setting_fips_mode = 166,
  expecting_an_hmac_key = 174,
  expecting_an_rsa_key = 127,
  expecting_a_dh_key = 128,
  expecting_a_dsa_key = 129,
  expecting_a_ec_key = 142,
  expecting_a_poly1305_key = 164,
  expecting_a_siphash_key = 175,
  fetch_failed = 202,
  final_error = 188,
  fips_mode_not_supported = 167,
  get_raw_key_failed = 182,
  illegal_scrypt_parameters = 171,
  inaccessible_domain_parameters = 204,
  inaccessible_key = 203,
  initialization_error = 134,
  input_not_initialized = 111,
  invalid_custom_length = 185,
  invalid_digest = 152,
  invalid_fips_mode = 168,
  invalid_iv_length = 194,
  invalid_key = 163,
  invalid_key_length = 130,
  invalid_operation = 148,
  invalid_provider_functions = 193,
  invalid_salt_length = 186,
  keygen_failure = 120,
  keymgmt_export_failure = 205,
  key_setup_failed = 180,
  memory_limit_exceeded = 172,
  message_digest_is_null = 159,
  method_not_supported = 144,
  missing_parameters = 103,
  not_able_to_copy_ctx = 190,
  not_xof_or_invalid_length = 178,
  no_cipher_set = 131,
  no_default_digest = 158,
  no_digest_set = 139,
  no_import_function = 206,
  no_keymgmt_available = 199,
  no_keymgmt_present = 196,
  no_key_set = 154,
  no_operation_set = 149,
  only_oneshot_supported = 177,
  operation_not_supported_for_this_keytype = 150,
  operaton_not_initialized = 151,
  parameter_too_large = 187,
  partially_overlapping = 162,
  pbkdf2_error = 181,
  pkey_application_asn1_method_already_registered = 179,
  private_key_decode_error = 145,
  private_key_encode_error = 146,
  public_key_not_rsa = 106,
  too_many_records = 183,
  unknown_cipher = 160,
  unknown_digest = 161,
  unknown_key_type = 207,
  unknown_option = 169,
  unknown_pbe_algorithm = 121,
  unsupported_algorithm = 156,
  unsupported_cipher = 107,
  unsupported_keylength = 123,
  unsupported_key_derivation_function = 124,
  unsupported_key_size = 108,
  unsupported_number_of_rounds = 135,
  unsupported_prf = 125,
  unsupported_private_key_algorithm = 118,
  unsupported_salt_type = 126,
  update_error = 189,
  wrap_mode_not_allowed = 170,
  wrong_final_block_length = 109,
  xts_data_unit_is_too_large = 191,
  xts_duplicated_keys = 192,
};

enum class engine {
  already_loaded = 100,
  argument_is_not_a_number = 133,
  cmd_not_executable = 134,
  command_takes_input = 135,
  command_takes_no_input = 136,
  conflicting_engine_id = 103,
  ctrl_command_not_implemented = 119,
  dso_failure = 104,
  dso_not_found = 132,
  engines_section_error = 148,
  engine_configuration_error = 102,
  engine_is_not_in_list = 105,
  engine_section_error = 149,
  failed_loading_private_key = 128,
  failed_loading_public_key = 129,
  finish_failed = 106,
  id_or_name_missing = 108,
  init_failed = 109,
  internal_list_error = 110,
  invalid_argument = 143,
  invalid_cmd_name = 137,
  invalid_cmd_number = 138,
  invalid_init_value = 151,
  invalid_string = 150,
  not_initialised = 117,
  not_loaded = 112,
  no_control_function = 120,
  no_index = 144,
  no_load_function = 125,
  no_reference = 130,
  no_such_engine = 116,
  unimplemented_cipher = 146,
  unimplemented_digest = 147,
  unimplemented_public_key_method = 101,
  version_incompatibility = 145,
};

enum class http {
  asn1_len_exceeds_max_resp_len = 108,
  connect_failure = 100,
  error_parsing_asn1_length = 109,
  error_parsing_content_length = 119,
  error_parsing_url = 101,
  error_receiving = 103,
  error_sending = 102,
  inconsistent_content_length = 120,
  max_resp_len_exceeded = 117,
  missing_asn1_encoding = 110,
  missing_content_type = 121,
  missing_redirect_location = 111,
  received_error = 105,
  received_wrong_http_version = 106,
  redirection_from_https_to_http = 112,
  redirection_not_enabled = 116,
  response_line_too_long = 113,
  response_parse_error = 104,
  sock_not_supported = 122,
  status_code_unsupported = 114,
  tls_not_enabled = 107,
  too_many_redirections = 115,
  unexpected_content_type = 118,
};

enum class io {
  accept = 100,
  addrinfo_address_is_not_af_inet = 141,
  ambiguous_host_or_service = 129,
  bad_fopen_mode = 101,
  broken_pipe = 124,
  connect_error = 103,
  connect_timeout = 147,
  gethostbyname_address_is_not_af_inet = 107,
  getsockname = 132,
  getsocketname_truncated_address = 133,
  getting_socktype = 134,
  invalid_argument = 125,
  invalid_socket = 135,
  in_use = 123,
  length_too_long = 102,
  listen_v6_only = 136,
  lookup_returned_nothing = 142,
  malformed_host_or_service = 130,
  nbio_connect_error = 110,
  no_accept_address_or_service_specified = 143,
  no_hostname_or_service_specified = 144,
  no_port_defined = 113,
  no_such_file = 128,
  null_parameter = 115,
  transfer_error = 104,
  transfer_timeout = 105,
  unable_to_bind_socket = 117,
  unable_to_create_socket = 118,
  unable_to_keepalive = 137,
  unable_to_listen_socket = 119,
  unable_to_nodelay = 138,
  unable_to_reuse_address = 139,
  unavailable_ip_family = 145,
  uninitialized = 120,
  unknown_info_type = 140,
  unsupported_ip_family = 146,
  unsupported_method = 121,
  unsupported_protocol_family = 131,
  write_to_read_only_bio = 126,
  wsastartup = 122,
};

} /* namespace aegis */

#endif /* AEGIS_ERROR_HPP */
